# Datatypes

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
a  = tf.constant(2)
print(a) # shape is ()

Tensor("Const:0", shape=(), dtype=int32)


In [3]:
a  = tf.constant(np.array([1,2,3])) # can supply a Python object or numpy object to a constant
print(a) # shape is ()

Tensor("Const_1:0", shape=(3,), dtype=int64)


In [4]:
a = tf.constant([1, 2, 3], name="myconst")
print(a) # shape is (3, )

Tensor("myconst:0", shape=(3,), dtype=int32)


In [5]:
a = np.zeros((3, 3)) # Create a 3x3 matrix filled with zero
print(a)
b = tf.zeros((3, 3)) # Create a 3x3 tensor filled with zero
print(b)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
Tensor("zeros:0", shape=(3, 3), dtype=float32)


In [6]:
a = np.ones((3, 3)) # Create a 3x3 matrix filled with ones
print(a)
b = tf.ones((3, 3)) # Create a 3x3 tensor filled with ones
print(b)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
Tensor("ones:0", shape=(3, 3), dtype=float32)


In [7]:
a = tf.fill((3, 3,), 20) # Fill a 3x3 matrix with 20s
print(a) # The print does not show the values

# To see the values in the matrix, we will start an 
# instance of the session and call the run method on it.
with tf.Session() as sess1:
    print(sess1.run(a))

Tensor("Fill:0", shape=(3, 3), dtype=int32)
[[20 20 20]
 [20 20 20]
 [20 20 20]]


In [31]:
'''
In-class activity: Create a tensor, A with constant() with value -11. Create another tensor, B  with 
value 9. Add the tensors, and call it C. Then run C and print the output. 
'''

A = tf.constant(-11)
B = tf.constant(9)
C = A+B

print('A', A)
print('B', B)
print('C', C)

with tf.Session() as sess1:
    print(sess1.run(C))

A Tensor("Const_12:0", shape=(), dtype=int32)
B Tensor("Const_13:0", shape=(), dtype=int32)
C Tensor("add_9:0", shape=(), dtype=int32)
-2


In [34]:
'''
In-class activity: Create a tensor, D with constant() with values [7, 8, 10]. Create another tensor, 
E of size (3, ) using fill() that has value 10. Add the tensors, and call it F.
Then run F and print the output. 
'''

D = tf.constant([7,8,10])
E = tf.fill((3, ), 10)
F = D+E

print('D', D)
print('E', E)
print('F', F)

with tf.Session() as sess2:
    print(sess2.run(F))

D Tensor("Const_16:0", shape=(3,), dtype=int32)
E Tensor("Fill_6:0", shape=(3,), dtype=int32)
F Tensor("add_12:0", shape=(3,), dtype=int32)
[17 18 20]


In [10]:
# Create a linearly spaced 20 numbers from 1 to 10 
# The three values are start, end, number of values. 
# The first two are float and the last value is an int.
linval = np.linspace(1.0, 10.0, 20)
print(linval) # This print statement prints the value stored
a = tf.constant(linval) # Convert to a tensorflow tensor
print(a) # This does not print the value stored

[  1.           1.47368421   1.94736842   2.42105263   2.89473684
   3.36842105   3.84210526   4.31578947   4.78947368   5.26315789
   5.73684211   6.21052632   6.68421053   7.15789474   7.63157895
   8.10526316   8.57894737   9.05263158   9.52631579  10.        ]
Tensor("Const_2:0", shape=(20,), dtype=float64)


In [11]:
# The three values are start, end, number of values. End value is included.
# The first two are float and the last value is an int.

# Directly create a tensor without using linspace as in the 
# previous example

# If the first 2 values are int, tensorflow throws an error.
a = tf.linspace(1.0, 10.0, 20)
print(a)

Tensor("LinSpace:0", shape=(20,), dtype=float32)


In [12]:
# Another mechanism to create linearly space numbers is to use range
# linspace takes start, end and number of values while
# range takes start, limit, delta. The limit is not included. 
a = tf.range(1, 10, 0.5)
print(a)
with tf.Session() as sess1:
    print(sess1.run(a))

Tensor("range:0", shape=(18,), dtype=float32)
[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.
  8.5  9.   9.5]


In [13]:
ra = np.array([[1, 2],[7, 8]])
a = tf.placeholder(tf.float32, shape=(2,2))
b = tf.matmul(a, a)
with tf.Session() as sess:
    print(sess.run(b, feed_dict={a: ra}))

[[ 15.  18.]
 [ 63.  78.]]


In [14]:
W = tf.Variable(tf.constant([2, 3, 5], name="weights"))
biases = tf.Variable(tf.constant([1, -1, 1], name="biases"))

m = tf.add(W, biases)
init_all_op = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init_all_op)
    print(sess.run(m))

[3 2 6]


In [15]:
W = tf.constant([2, 3, 5], name="weights")
biases = tf.constant([1, -1, 1], name="biases")

m1 = tf.add(W, biases)
m2 = tf.add(W, biases)

sess = tf.InteractiveSession()
m1_out = m1.eval()
m2_out = m2.eval()
print(m1_out)
print(m2_out)
sess.close()

[3 2 6]
[3 2 6]


In [40]:
'''
In-class activity: Create a placeholder tensor, W1 of shape (2, 2). Create a numpy array I with 
values [1, 0], [0, 1]. Define another tensor M that computes W1*W1. Run M and feed I. Print M.
'''

W1 = tf.placeholder(tf.float32, shape=(2,2))
I = np.array([[1,0],[0,1]])
M = W1*W1

with tf.Session() as sess:
    print(sess.run(M, feed_dict={W1: I}))

[[ 1.  0.]
 [ 0.  1.]]


In [43]:
'''
In-class activity: Create a tensor, v1 using Variable() with values [2, 4, 6]. 
Create another tensor, v2 using Variable() with values [4 6 8]. Define v3 as the sum of v1 and v2. 
initialize the variable values and then run and print v3.
'''

v1 = tf.Variable(tf.constant([2, 4, 6], name="weights"))
v2 = tf.Variable(tf.constant([4, 6, 8], name="biass"))
v3 = v1+v2
init_all_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_all_op)
    print(sess.run(v3))

[ 6 10 14]


In [44]:
tf.summary.FileWriter('./XOR_graph1', sess.graph)

In [22]:
test = (5,)*6

In [20]:
print(type(test))

<class 'tuple'>


In [23]:
test

(5, 5, 5, 5, 5, 5)