# Basic math functions

In [1]:
# %%latex

In [2]:
import tensorflow as tf

In [3]:
t1 = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.constant([[7, 8, 9], [0, 1, 2]])
print(t1, t2)
t3 = tf.add(t1, t2) # Element by element addition
print(t3)
with tf.Session() as sess1:
    print(sess1.run(t3))
# similarly there is sub for subtraction, mul for multiplication etc.

Tensor("Const:0", shape=(2, 3), dtype=int32) Tensor("Const_1:0", shape=(2, 3), dtype=int32)
Tensor("Add:0", shape=(2, 3), dtype=int32)
[[ 8 10 12]
 [ 4  6  8]]


In [4]:
# t1 and t2 must be of the same type
# for example in the following code, t1 is of dtype int32 while t2 is of 
# dtype float32 in this case, the addition will fail
t1 = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.constant([[7, 8, 9], [0, 1, 2]], tf.float32)
t3 = tf.add(t1, t2) # this will fail as t1 and t2 are not of the same type

TypeError: Input 'y' of 'Add' Op has type float32 that does not match type int32 of argument 'x'.

In [5]:
t1 = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.constant([[7, 8, 9], [0, 1, 2]])
t3 = tf.truediv(t1, t2) # Element by element division which returns floating point value
with tf.Session() as sess1:
    print(sess1.run(t3))
# Note that the zero division did not generate ZeroDivisionError as in Python
# instead it creates a value of inf in the tensor

[[ 0.14285714  0.25        0.33333333]
 [        inf  5.          3.        ]]


In [6]:
t1 = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.constant([[7, 8, 9], [0, 1, 2]])
t3 = tf.floordiv(t2, t1) # Element by element division which returns integer value
with tf.Session() as sess1:
    print(sess1.run(t3))
print("The dtype of t3 is ", t3.dtype) # check the value of dtype of t3 and it is int32

[[7 4 3]
 [0 0 0]]
The dtype of t3 is  <dtype: 'int32'>


# Matrix functions

In [7]:
# matrix multiplication
t1 = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.constant([[7, 8, 9], [0, 1, 2]])
t3 = tf.transpose(t2, perm=[1, 0]) # transpose t2, so that we can perform matrix multiplication
t4 = tf.matmul(t1, t3) # matrix multiplication 
with tf.Session() as sess1:
    print(sess1.run(t4))

[[ 50   8]
 [122  17]]


In [8]:
# matrix inverse
# The matrix_inverse expects that the input tensor whose
# 1. inner most dimension is square (i.e.,) shape=[..., M, M]
# 2. dtype is float32 or float64.
t1 = tf.constant([[1, 12, 43], [45, 57, 68], [17, 58, 89]], tf.float32)
t2 = tf.matrix_inverse(t1) # inverse t1
with tf.Session() as sess1:
    print(sess1.run(t2))

[[ 0.03010346  0.03802261 -0.04359535]
 [-0.07596523 -0.01711817  0.04978136]
 [ 0.04375533  0.00389292 -0.01287863]]


A reduce operation takes a tensor and converts it to a tensor of smaller dimension. There are a number of reduce operations. The name of the method indicates the operation used for reduction. 

For example the function reduce_sum sums all the values in the tensor, the function reduce_prod multiplies all the values in the tensor.

In [9]:
t1 = tf.constant([[1, 2, 3], [4, 5, 6]])
t_sum = tf.reduce_sum(t1)   # This is equal to the sum of all the values in t1
t_prod = tf.reduce_prod(t1) # This is equal to the product of all the values in t1
t_min = tf.reduce_min(t1)   # This is equal to the minimum of all the values in t1
with tf.Session() as sess1:
    print(sess1.run(t_sum))
    print(sess1.run(t_prod)) 
    print(sess1.run(t_min)) 

21
720
1


In [10]:
t1 = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.constant([[7, 8, 9], [0, 1, 2]])
t_elemsum = tf.accumulate_n([t1, t2, t1])  
# This is equal to element by element sum of t1 + t2 + t1
with tf.Session() as sess1:
    print(sess1.run(t_elemsum))

[[ 9 12 15]
 [ 8 11 14]]


In [11]:
t1 = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.constant([[7, 8, 9], [0, 1, 2]])
t3 = tf.cumsum([t1, t2, t1], axis=0) # cumulative sum
with tf.Session() as sess1:
    print(sess1.run(t3)) 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 8 10 12]
  [ 4  6  8]]

 [[ 9 12 15]
  [ 8 11 14]]]


In [12]:
t1 = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.constant([[7, 8, 9], [0, 1, 2]])
t3 = tf.cumprod([t1, t2, t1], axis=0) # cumulative product
with tf.Session() as sess1:
    print(sess1.run(t3)) 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7 16 27]
  [ 0  5 12]]

 [[ 7 32 81]
  [ 0 25 72]]]


In [13]:
'''
In-class activity: Create a tensor, T1 = [[384,396,408], [180,192,204]] and T2 = [[4, 3, 12], [2, 6, 12]]
Find the following:
1) divide T1 with T2
2) find cumsum of T1, T2 and T2
'''

'\nIn-class activity: Create a tensor, T1 = [[384,396,408], [180,192,204]] and T2 = [[4, 3, 12], [2, 6, 12]]\nFind the following:\n1) divide T1 with T2\n2) find cumsum of T1, T2 and T2\n'

In [14]:
# tf.cond works like if-else statement and allows branching in a graph

# Implementing RELU using tf.cond
zeroval = tf.constant(0.0)
x = tf.placeholder(tf.float32, shape=())
reluval = tf.cond(x <=0, lambda: zeroval, lambda: x)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(reluval, feed_dict={x: -2.25}))

0.0


In [15]:
# In-class activity: Implement leaky RELU based on the formula below.

In [16]:
%%latex
f(x)=\begin{cases}x&{\mbox{if }}x>0\\0.01x&{\mbox{otherwise}}\end{cases}

<IPython.core.display.Latex object>

In [17]:
# tf.cond works like if-else statement and allows branching in a graph

# Implementing RELU using tf.cond
zeroval = tf.constant(0.0)
x = tf.placeholder(tf.float32, shape=())
reluval = tf.cond(x <=0, lambda: x*0.01, lambda: x)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(reluval, feed_dict={x: -2.25}))

-0.0225
