# Simple examples

In [1]:
import tensorflow as tf
import numpy as np

In [19]:
# generate random values 
# build powerball lottery number generator
# first number is between [1, 59]
# last number is between [1, 35]
# maxval is inclusive
mainno = tf.random_uniform(shape=(5, ), minval=1, maxval=59, dtype=tf.int32)
lastno = tf.random_uniform((1, ), minval=1, maxval=35, dtype=tf.int32)
# concatenate the two tensors along dimension 0
powerballno = tf.concat([mainno, lastno], 0)
# In the print statement, you will notice that all these variables
# are Tensor objects and not the value themselves
print(mainno, lastno, powerballno)
# Start a session, so that all these variables can be evaluated.
with tf.Session() as sess1:
    powerballval = sess1.run(powerballno)
print(powerballval, type(powerballval))

Tensor("random_uniform_22:0", shape=(5,), dtype=int32) Tensor("random_uniform_23:0", shape=(1,), dtype=int32) Tensor("concat_11:0", shape=(6,), dtype=int32)
[56  2 37 34 25  6] <class 'numpy.ndarray'>


In the code above, the powerballno is evaluated and a set of 6 random values are generated. The output of the run() is a numpy array as seen in the output of the print function.

In [15]:
# power ball number generator with more mysteries
mainno = tf.random_uniform(shape=(5, ), minval=1, maxval=59, dtype=tf.int32)
lastno = tf.random_uniform((1, ), minval=1, maxval=35, dtype=tf.int32)
powerballno = tf.concat([mainno, lastno], 0)
with tf.Session() as sess1:
    print(sess1.run(mainno))
    print(sess1.run(lastno))
    print(sess1.run(powerballno))

[53 28 35 35 39]
[19]
[27 55 33 43 45  5]


In [22]:
mainno = [1, 2, 4, 5, 6]
lastno = 12

powerballno = tf.concat([mainno, lastno], 0)
with tf.Session() as sess1:
    print(sess1.run(mainno))
    print(sess1.run(lastno))
    print(sess1.run(powerballno))

ValueError: Shape must be rank 1 but is rank 0 for 'concat_14' (op: 'ConcatV2') with input shapes: [5], [], [].

In [17]:
with tf.Session() as sess1:
    print(sess1.run(mainno))
    print(sess1.run(lastno))
    print(sess1.run(powerballno))

[53 28 35 35 39]
[19]
[27 55 33 43 45  5]


If you notice the output, the first run call evaluates the tensor mainno and returns a tensor of length 5 filled with random values. The secondcall returns a tensor of length 1 filled with a random value. 

You would imagine that the output of last run statement would contain the values of first run and the second run call. However, it is very different. The reason is in Tensorflow, the functions like tf.random_uniform, tf.concat etc. are evaluated only at the call to run(). So, when the last run is called, the tf.concat function is evaluated. The tf.concat function (or ops) is in turn built with two other ops calls namely the two tf.random_uniform ops used for mainno and lastno.   

Thus, in the above code, mainno and lastno ops are called twice, once for the first and second run function calls and then again by the last run function call.

If the above code is run multiple times, it will generate different patterns of random numbers. What if you want tensorflow to generate the same random pattern.

In [4]:
# power ball number generator with op-level seed
mainno = tf.random_uniform(shape=(5, ), minval=1, maxval=59, \
                           dtype=tf.int32, seed=1)
lastno = tf.random_uniform((1, ), minval=1, maxval=35, \
                           dtype=tf.int32, seed=1)
powerballno = tf.concat([mainno, lastno], 0)
with tf.Session() as sess1:
    print(sess1.run(powerballno))
    
with tf.Session() as sess2:
    print(sess2.run(powerballno))

[14 20 56 19 44 26]
[14 20 56 19 44 26]


By specifying a constant seed, a random pattern of numbers are generated and at every run, the pattern will remain the same irrespective of the session. This is an example of op-level seed. This method is useful if you need to generate the same repeatable sequence for an op across sessions.

If there are many operations, it will be inconvenient to provide seed for each one separately. You can instead choose to provide a graph level seed using tf.set_random_seed. This method is useful if you need to generate random numbers created by all ops be repeatable across sessions in the same graph execution.

In [5]:
# Alternate seeding mechanism by seeding the graph
tf.set_random_seed(3457)
mainno = tf.random_uniform(shape=(5, ), minval=1, maxval=59, dtype=tf.int32)
lastno = tf.random_uniform((1, ), minval=1, maxval=35, dtype=tf.int32)
powerballno = tf.concat([mainno, lastno], 0)
with tf.Session() as sess1:
    print(sess1.run(powerballno))

with tf.Session() as sess2:
    print(sess2.run(powerballno))

[44 41 10 19 37 12]
[44 41 10 19 37 12]


In the example above, the two sessions: sess1 and sess2 produced the same set of random numbers. However, with each run of the code, the number generated are different for every run. 

#### Obtain the value of pi using Gregory-Madhava-Leibiniz series
Gregory-Madhava-Leibiniz series 

![Gregory-Madhava-Leibiniz series](gml.png)

In [6]:
# find value of pi using tensorflow
n = 10000000
# Create an empty numpy array
numerator_np = np.ones((n,), np.float64)
# Change the alternate values to -1
numerator_np[1::2] = -1.0
print(numerator_np.shape)
# Convert numpy array to tensor
numerator = tf.constant(numerator_np)
print(numerator)
# Create denominator with values 1, 3, 5, ... up to 2n
denominator = tf.linspace(1.0, 2.0*n, n)
# Linspace is creating a 32-bit float. converting it to 64-bit.
denominator = tf.cast(denominator, tf.float64)
pival = tf.reduce_sum(tf.div(numerator, denominator))
print(pival)
sess = tf.InteractiveSession()
# A tensor returned by Session.run or eval is a NumPy array.
pival_out = pival.eval()
sess.close()
print(4.0*pival_out)

(10000000,)
Tensor("Const:0", shape=(10000000,), dtype=float64)
Tensor("Sum:0", shape=(), dtype=float64)
3.14159258716


In [7]:
'''
In-class activity: If T = [[121, 99, 145], [45, 119, 225], [235, 170, 723]]
Find
1) the minimum value in T and print it
2) the maximum value in T and print it
'''

'\nIn-class activity: If T = [[121, 99, 145], [45, 119, 225], [235, 170, 723]]\nFind\n1) the minimum value in T and print it\n2) the maximum value in T and print it\n'

In [8]:
'''
In-class activity: If T = [[121, 99, 145], [45, 119, 0], [235, 170, 723]]. Let eps = 0.001. 
Find
1) add eps to every element in T
2) compute the log of the tensor that is obtained in 1).
'''

'\nIn-class activity: If T = [[121, 99, 145], [45, 119, 0], [235, 170, 723]]. Let eps = 0.001. \nFind\n1) add eps to every element in T\n2) compute the log of the tensor that is obtained in 1).\n'

In [9]:
'''
In-class activity
'''
import cv2
import tensorflow as tf

logoimg = cv2.imread('tensorflow_logo_gray.png',0)
print(logoimg.shape)

maxpixelvalue = tf.constant(255, dtype=tf.float32)
img = tf.placeholder(tf.float32, shape=None)
eps = tf.constant(1e-5, dtype=tf.float32)

'''
1. Apply log transformation to the placeholder image, img. Make sure to add eps to it, so that we do not calculate log(0)

2. Calculate the maximum value in the tensor from the previous step across all dimensions

3. Calculate the minimum value in the tensor from the previous step across all dimensions

4. Scale the tensor, so that the resultant tensor can only have values from 0 to 255. Use the formula 
maxpixelvalue*(logval-min)/(max-min)
'''

print(scaledlogtransformed)

with tf.Session() as sess1:
    scaledimg = sess1.run(scaledlogtransformed, feed_dict={img: logoimg})
    
cv2.imwrite('logoimage.png', scaledimg)

(300, 352)


NameError: name 'scaledlogtransformed' is not defined