# Transformation

## Casting

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
t1 = tf.constant([1, 2, 3]) # The datatype for individual element is int32
print(t1)
t2 = tf.cast(t1, tf.float32)  # Cast the individual elements from int32 to float32
print(t2)

Tensor("Const:0", shape=(3,), dtype=int32)
Tensor("Cast:0", shape=(3,), dtype=float32)


In [3]:
# tf.cast is generic method that can be used to convert from one dtype to another
# There are also specialized method such as tf.to_float32()
t2 = tf.to_float(t1)  # Specialized function. 
print(t2)

Tensor("ToFloat:0", shape=(3,), dtype=float32)


In [4]:
'''
In-class activity: Define a tensor, T1 with values [31 37 41] then print the dtype of this tensor. 
Then change T1's dtype to float using 
1) to_float()
2) cast()
'''

"\nIn-class activity: Define a tensor, T1 with values [31 37 41] then print the dtype of this tensor. \nThen change T1's dtype to float using \n1) to_float()\n2) cast()\n"


## Shapes

In [5]:
# create a 4D tensor of shape 3, 4, 5, 6
t1 = tf.zeros((3, 4, 5, 6)) 
t2 = tf.size(t1) # Size gives the number of elements
with tf.Session() as sess1:
    print(sess1.run(t2))

360


In [6]:
# create a 4D tensor of shape 3, 4, 5, 6
t1 = tf.zeros((3, 4, 5, 6))
t2 = tf.shape(t1) # shape gives the size of each dimension
with tf.Session() as sess1:
    print(sess1.run(t2))

[3 4 5 6]


In [7]:
t1 = tf.zeros((3, 4, 5, 6))
t2 = tf.reshape(t1, (12, 5, 6)) # reshape tensor
print(t1, t2)
# Note that t1 is of shape 3, 4, 5, 6 while t2 is of shape 12, 5, 6

Tensor("zeros_2:0", shape=(3, 4, 5, 6), dtype=float32) Tensor("Reshape:0", shape=(12, 5, 6), dtype=float32)


In [8]:
t1 = tf.zeros((3, 4, 1, 6))
t2 = tf.squeeze(t1) # squeeze removes dimensions of size 1
print(t1)
print(t2)
# Note that t1 is of shape 3, 4, 1, 6 while t2 is of shape 3, 4, 6. 
# The 3rd dimension of size 1 is removed

Tensor("zeros_3:0", shape=(3, 4, 1, 6), dtype=float32)
Tensor("Squeeze:0", shape=(3, 4, 6), dtype=float32)


The syntax for slice is tf.slice(inputtensor, begin, size)

begin has the same shape as the tensor and it contains the starting point in each dimension. In this example, the value of begin is [2, 0].  Thus in the first dimension (row) we begin at position 2 and  in the second dimension (column) we begin at 0. 

size has the same shape as the tensor and it contains the number of elements in each dimension. In this example, the value of size is [1, 2]. Thus we are indicating that we need one row and two columns to be sliced.

** NOTE: begin is zero based and size is 1 based. **

In [24]:
t1 = tf.constant([[1, -1, 3], [-11, 2, 1], [-5, 6, 9]])
t2 = tf.slice(t1, [1, 0], [2, 2])

with tf.Session() as sess1:
    print(sess1.run(t1))
    print(sess1.run(t2))

[[  1  -1   3]
 [-11   2   1]
 [ -5   6   9]]
[[-11   2]
 [ -5   6]]


In [27]:
'''
In-class activity: Create a tensor with shape (12, 1, 14) and then drop the dimension 1.
'''
t1 = tf.zeros((12, 1, 14))
t2 = tf.squeeze(t1) # squeeze removes dimensions of size 1
print(t1)
print(t2)

Tensor("zeros_4:0", shape=(12, 1, 14), dtype=float32)
Tensor("Squeeze_1:0", shape=(12, 14), dtype=float32)


In [26]:
'''
In-class activity: If T1 is a tensor with values [[12, 13, 11], [9, 11, 9], [2, 5, 7]]. 
How can we slice T1 so that we get tensor with values [9, 11, 9].
'''
t1 = tf.constant([[12, 13, 11], [9, 11, 9], [2, 5, 7]])
t2 = tf.slice(t1, [1, 0], [1, 3])

with tf.Session() as sess1:
    print(sess1.run(t1))
    print(sess1.run(t2))

[[12 13 11]
 [ 9 11  9]
 [ 2  5  7]]
[[ 9 11  9]]


In [18]:
L = [5, 6, 7, 8]
L[0:3]

[5, 6, 7]